import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import localFont from "next/font/local";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/home/Header";
// import { img } from "motion/react-client";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", ], // Add the desired font weights as needed
});

const ClashDisplay = localFont({
  variable: "--font-clash-display",
  src: [
    {
      path: "./fonts/ClashDisplay-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className=''>
      <body
        className={`${poppins.variable} ${ClashDisplay.variable }  antialiased bg-background font-poppins`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}